export const mockClubs = [
  {
    id: '1',
    name: '기독학생회',
    logo: '/logos/club1.png',
    tags: ['신앙', '친목'],
    state: '모집중',
    division: '중동',
    classification: '종교',
    description: '신앙 생활을 함께하는 클럽입니다.',
  },
  {
    id: '2',
    name: 'WAP',
    logo: '/logos/club2.png',
    tags: ['프로그래밍', '개발'],
    state: '모집중',
    division: '중동',
    classification: '학술',
    description: '프로그래밍을 배우고 프로젝트를 진행합니다.',
  },
  {
    id: '3',
    name: '축구 동아리',
    logo: '/logos/club3.png',
    tags: ['운동', '친목'],
    state: '모집중',
    division: '중동',
    classification: '운동',
    description: '축구를 즐기는 동아리입니다.',
  },
  {
    id: '4',
    name: '음악 동호회',
    logo: '/logos/club4.png',
    tags: ['공연', '밴드'],
    state: '모집예정',
    division: '중동',
    classification: '공연',
    description: '밴드 활동 및 공연을 진행합니다.',
  },
  {
    id: '5',
    name: '자원봉사팀',
    logo: '/logos/club5.png',
    tags: ['봉사', '사회활동'],
    state: '모집중',
    division: '중동',
    classification: '봉사',
    description: '지역사회 봉사를 위한 클럽입니다.',
  },
  {
    id: '6',
    name: '사진 동호회',
    logo: '/logos/club6.png',
    tags: ['사진', '취미'],
    state: '모집마감',
    division: '중동',
    classification: '취미교양',
    description: '사진 촬영 및 전시회를 개최하는 클럽입니다.',
  },
  {
    id: '7',
    name: '로봇 연구회',
    logo: '/logos/club7.png',
    tags: ['로봇', '공학'],
    state: '모집중',
    division: '중동',
    classification: '학술',
    description: '로봇을 연구하고 개발하는 클럽입니다.',
  },
  {
    id: '8',
    name: '헬스 동아리',
    logo: '/logos/club8.png',
    tags: ['헬스', '운동'],
    state: '모집마감',
    division: '중동',
    classification: '운동',
    description: '헬스를 통해 건강을 유지하는 클럽입니다.',
  },
  {
    id: '9',
    name: '프론트엔드 개발자 모임',
    logo: '/logos/club9.png',
    tags: ['프론트엔드', '개발'],
    state: '모집중',
    division: '중동',
    classification: '학술',
    description: '프론트엔드 기술을 공부하고 프로젝트를 진행합니다.',
  },
  {
    id: '10',
    name: '국제 교류 동아리',
    logo: '/logos/club10.png',
    tags: ['교류', '언어교환'],
    state: '모집마감',
    division: '중동',
    classification: '취미교양',
    description: '국제 학생들과의 문화 및 언어 교류 활동을 합니다.',
  },
  {
    id: '11',
    name: '드론 동아리',
    logo: '/logos/club11.png',
    tags: ['드론', '항공'],
    state: '모집중',
    division: '중동',
    classification: '학술',
    description: '드론 조종 및 항공 촬영을 배우는 클럽입니다.',
  },
  {
    id: '12',
    name: '요리 연구회',
    logo: '/logos/club12.png',
    tags: ['요리', '미식'],
    state: '모집예정',
    division: '중동',
    classification: '취미교양',
    description: '다양한 요리법을 연구하고 시연하는 클럽입니다.',
  },
  {
    id: '13',
    name: '연극 동아리',
    logo: '/logos/club13.png',
    tags: ['연극', '공연'],
    state: '모집중',
    division: '중동',
    classification: '공연',
    description: '연극 제작 및 공연을 통해 창의력을 발휘하는 클럽입니다.',
  },
  {
    id: '14',
    name: '환경 보호 동아리',
    logo: '/logos/club14.png',
    tags: ['환경', '보호'],
    state: '모집마감',
    division: '중동',
    classification: '봉사',
    description: '환경 보호 활동 및 캠페인을 진행하는 클럽입니다.',
  },
  {
    id: '15',
    name: '자전거 동호회',
    logo: '/logos/club15.png',
    tags: ['자전거', '여행'],
    state: '모집중',
    division: '중동',
    classification: '운동',
    description: '자전거 투어 및 관련 활동을 즐기는 클럽입니다.',
  },
  {
    id: '16',
    name: '애니메이션 제작 동아리',
    logo: '/logos/club16.png',
    tags: ['애니메이션', '영상'],
    state: '모집예정',
    division: '중동',
    classification: '학술',
    description: '애니메이션 제작 및 편집을 배우는 클럽입니다.',
  },
  {
    id: '17',
    name: '천체 관측 동아리',
    logo: '/logos/club17.png',
    tags: ['천문학', '관측'],
    state: '모집중',
    division: '중동',
    classification: '학술',
    description: '별과 행성을 관측하며 우주를 탐구하는 클럽입니다.',
  },
  {
    id: '18',
    name: '댄스 동아리',
    logo: '/logos/club18.png',
    tags: ['댄스', '퍼포먼스'],
    state: '모집중',
    division: '중동',
    classification: '공연',
    description: '다양한 댄스 장르를 배우고 공연하는 클럽입니다.',
  },
  {
    id: '19',
    name: '독서 토론 모임',
    logo: '/logos/club19.png',
    tags: ['독서', '토론'],
    state: '모집마감',
    division: '중동',
    classification: '취미교양',
    description: '책을 읽고 다양한 주제로 토론하는 클럽입니다.',
  },
  {
    id: '20',
    name: '비즈니스 전략 동아리',
    logo: '/logos/club20.png',
    tags: ['비즈니스', '전략'],
    state: '모집중',
    division: '중동',
    classification: '학술',
    description: '비즈니스 전략을 연구하고 실습하는 클럽입니다.',
  },
];
